[package]
name = "crystal_plus"
version = "1.3.0"
edition = "2024"

[dependencies]
discord-presence = "2.1.0"
glob = "0.3.3"
mp3-duration = "0.1.10"
pancurses = { version = "0.17.0", features = ["win32"] }
rand = "0.9.2"
rodio = "0.21.1"
libc = "0.2"
id3 = "1.16.3"
